Feature rf gu 1
gianwario/BeeHave pull request #45
Opened 2023-01-12 21:02 UTC by IreneGaita

2023-01-12 21:14 UTC, Luigi11162 requested changes

2023-01-12 21:14 UTC, Luigi11162 commented on Website/flaskr/gestione_adozioni/GestioneAdozioniService.py
> +def get_AlveariByApicoltore(id_apicoltore):
Rimuovere metodo ridondante

2023-01-12 21:14 UTC, Luigi11162 commented on Website/flaskr/gestione_adozioni/GestioneAdozioniService.py
> +def update_stato(id, covata_compatta, popolazione, polline, stato_cellette):
cambiare in aggiorna_stato

2023-01-13 11:11 UTC, Luigi11162 approved these changes

2023-01-13 11:12 UTC, andesrule commented on Website/flaskr/templates/inserimento_alveare.html
> +                      <label for="covata_compatta">La covata è compatta?</label><br>
Press ctrl+alt+L to intent files

2023-01-13 11:12 UTC, andesrule commented on Website/flaskr/templates/inserimento_alveare.html
> +                      <label for="tipo_fiore">Inserire il nome del fiore impollinato: </label>
Press ctrl+alt+L to intent files

2023-01-13 11:14 UTC, merged

2023-01-13 11:15 UTC, andesrule reviewed
Press ctrl+alt+L to indent files